# Generated by Django 3.2 on 2021-06-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numid', models.CharField(max_length=50, verbose_name='Identification')),
                ('pieceid', models.CharField(choices=[('CNI', "Carte Nationale d'Idientité"), ('NINA', 'NINA'), ('CIC', "Carte d'Idientité Consulaire"), ('PASSPORT', 'PASSPORT')], max_length=20, verbose_name="Pièce d'identité")),
                ('adresse', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=12)),
            ],
        ),
    ]
