# Generated by Django 3.2 on 2021-06-02 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.CharField(max_length=25, verbose_name='RIB')),
                ('proprietaire', models.CharField(max_length=50, verbose_name='Propriétaire')),
                ('nom_banque', models.CharField(max_length=50, verbose_name='Nom de la banque')),
                ('adresse_banque', models.CharField(max_length=250, verbose_name='Adresse de la banque')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du Projet')),
                ('resume', models.CharField(max_length=250, verbose_name='Description du Projet')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name="Photo d'Illustration du Projet")),
                ('secteur', models.CharField(max_length=50, verbose_name="Secteur d'Activité")),
                ('budget', models.FloatField(verbose_name='Budget du Projet')),
                ('statut', models.CharField(choices=[('SDI', "Stade d'Idée"), ('EGN', 'En Gestation'), ('JLC', 'Juste Lancé'), ('EAE', 'En Activité'), ('C', 'Cloturé')], max_length=30, verbose_name='Stade du Projet')),
                ('date_pub', models.DateTimeField(default=datetime.datetime(2021, 6, 2, 20, 1, 2, 617320), max_length=30, verbose_name='Date de Publication du Projet')),
                ('fiche_desc', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fichier de Presentation du Projet')),
            ],
        ),
    ]
