# Generated by Django 3.2 on 2021-06-09 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djago', '0002_compte_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djago.utilisateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 18, 46, 37, 13737), max_length=30, verbose_name='Date de Publication du Projet'),
        ),
    ]
