# Generated by Django 3.2 on 2021-06-09 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djago', '0003_auto_20210609_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=30, verbose_name='Date de Publication du Projet'),
        ),
    ]
