# Generated by Django 3.2 on 2021-06-09 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djago', '0005_alter_projet_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=30, verbose_name='Date de Publication du Projet'),
        ),
    ]
