# Generated by Django 3.2 on 2021-06-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djago', '0007_auto_20210623_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='proprietaire',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='djago.utilisateur', verbose_name='propriétaire'),
        ),
    ]
